### ISSUE TITLE
Readme publication links are dead

### ISSUE THREAD

**Issue by hulsed** [danceos/fail#10]
Update/remove the links in the below section of the ReadME--they no longer link to the associated PDFs
___________________________________________________
Please cite the EDCC paper if you want to refer to FAIL*:

H. Schirmeier, M. Hoffmann, C. Dietrich, M. Lenz, D. Lohmann, and O. Spinczyk. FAIL*: An open and versatile fault-injection framework for the assessment of software-implemented hardware fault tolerance. In Proceedings of the 11th European Dependable Computing Conference (EDCC '15), pages 245–255. IEEE Computer Society Press, Sept. 2015. PDF

H. Schirmeier. Efficient Fault-Injection-based Assessment of Software-Implemented Hardware Fault Tolerance. Dissertation, Technische Universität Dortmund, July 2016.

H. Schirmeier, M. Hoffmann, R. Kapitza, D. Lohmann, and O. Spinczyk. FAIL*: Towards a versatile fault-injection experiment framework. In G. Mühl, J. Richling, and A. Herkersdorf, editors, 25th International Conference on Architecture of Computing Systems (ARCS '12), Workshop Proceedings, volume 200 of Lecture Notes in Informatics, pages 201–210. German Society of Informatics, Mar. 2012. PDF

**Comment by schirmeier** [comment]
Thanks for bringing this to my attention! Will fix ASAP. For the time being, you can download all listed publications here: https://ess.cs.uos.de/danceos/publications.shtml
